# requestURI = commandHandler mapping
# board
/mvc/board/list.htm=days07.mvc.board.command.ListHandler
/mvc/board/write.htm=days07.mvc.board.command.WriteHandler
/mvc/board/view.htm=days07.mvc.board.command.ViewHandler
/mvc/board/edit.htm=days07.mvc.board.command.EditHandler
/mvc/board/delete.htm=days07.mvc.board.command.DeleteHandler

# member
/mvc/member/login.htm=days07.mvc.member.command.LoginHandler
/mvc/member/logout.htm=days07.mvc.member.command.LogoutHandler